const PIXEL = 4;

function Pixel({ x, y, color }) {
  return <rect x={x * PIXEL} y={y * PIXEL} width={PIXEL} height={PIXEL} fill={color} />;
}

const palette = {
  outline: "#0f1720",
  body: "#1f6b4f",
  bodySoft: "#57a988",
  belly: "#d5efe3",
  eye: "#ffffff",
  eyePupil: "#0f1720",
  blush: "#a3d8c1",
};

const pixels = [
  [5, 1, palette.outline],
  [6, 1, palette.outline],
  [7, 1, palette.outline],
  [8, 1, palette.outline],
  [9, 1, palette.outline],
  [4, 2, palette.outline],
  [5, 2, palette.body],
  [6, 2, palette.body],
  [7, 2, palette.bodySoft],
  [8, 2, palette.body],
  [9, 2, palette.body],
  [10, 2, palette.outline],
  [3, 3, palette.outline],
  [4, 3, palette.body],
  [5, 3, palette.body],
  [6, 3, palette.body],
  [7, 3, palette.bodySoft],
  [8, 3, palette.body],
  [9, 3, palette.body],
  [10, 3, palette.body],
  [11, 3, palette.outline],
  [3, 4, palette.outline],
  [4, 4, palette.body],
  [5, 4, palette.body],
  [6, 4, palette.eye],
  [7, 4, palette.eyePupil],
  [8, 4, palette.body],
  [9, 4, palette.body],
  [10, 4, palette.body],
  [11, 4, palette.outline],
  [2, 5, palette.outline],
  [3, 5, palette.body],
  [4, 5, palette.body],
  [5, 5, palette.body],
  [6, 5, palette.body],
  [7, 5, palette.body],
  [8, 5, palette.body],
  [9, 5, palette.body],
  [10, 5, palette.body],
  [11, 5, palette.body],
  [12, 5, palette.outline],
  [2, 6, palette.outline],
  [3, 6, palette.body],
  [4, 6, palette.body],
  [5, 6, palette.body],
  [6, 6, palette.body],
  [7, 6, palette.belly],
  [8, 6, palette.belly],
  [9, 6, palette.body],
  [10, 6, palette.body],
  [11, 6, palette.body],
  [12, 6, palette.outline],
  [1, 7, palette.outline],
  [2, 7, palette.body],
  [3, 7, palette.body],
  [4, 7, palette.body],
  [5, 7, palette.body],
  [6, 7, palette.belly],
  [7, 7, palette.belly],
  [8, 7, palette.belly],
  [9, 7, palette.body],
  [10, 7, palette.body],
  [11, 7, palette.body],
  [12, 7, palette.body],
  [13, 7, palette.outline],
  [2, 8, palette.outline],
  [3, 8, palette.body],
  [4, 8, palette.body],
  [5, 8, palette.body],
  [6, 8, palette.belly],
  [7, 8, palette.belly],
  [8, 8, palette.belly],
  [9, 8, palette.body],
  [10, 8, palette.body],
  [11, 8, palette.body],
  [12, 8, palette.outline],
  [3, 9, palette.outline],
  [4, 9, palette.body],
  [5, 9, palette.body],
  [6, 9, palette.body],
  [7, 9, palette.body],
  [8, 9, palette.body],
  [9, 9, palette.body],
  [10, 9, palette.body],
  [11, 9, palette.outline],
  [4, 10, palette.outline],
  [5, 10, palette.body],
  [6, 10, palette.blush],
  [7, 10, palette.body],
  [8, 10, palette.body],
  [9, 10, palette.body],
  [10, 10, palette.outline],
  [5, 11, palette.outline],
  [6, 11, palette.body],
  [7, 11, palette.body],
  [8, 11, palette.outline],
  [4, 12, palette.outline],
  [5, 12, palette.body],
  [6, 12, palette.outline],
  [8, 12, palette.outline],
  [9, 12, palette.body],
  [10, 12, palette.outline],
  [2, 13, palette.outline],
  [3, 13, palette.body],
  [4, 13, palette.body],
  [5, 13, palette.body],
  [6, 13, palette.body],
  [7, 13, palette.body],
  [8, 13, palette.body],
  [9, 13, palette.body],
  [10, 13, palette.body],
  [11, 13, palette.outline],
  [1, 14, palette.outline],
  [2, 14, palette.body],
  [3, 14, palette.body],
  [4, 14, palette.body],
  [5, 14, palette.body],
  [6, 14, palette.body],
  [7, 14, palette.body],
  [8, 14, palette.body],
  [9, 14, palette.body],
  [10, 14, palette.body],
  [11, 14, palette.body],
  [12, 14, palette.outline],
  [3, 15, palette.outline],
  [4, 15, palette.body],
  [5, 15, palette.outline],
  [8, 15, palette.outline],
  [9, 15, palette.body],
  [10, 15, palette.outline],
];

export default function Din0Sprite({ className = "", title = "Din_0 mascot" }) {
  return (
    <svg
      className={className}
      viewBox="0 0 56 64"
      role="img"
      aria-label={title}
      shapeRendering="crispEdges"
    >
      {pixels.map(([x, y, color]) => (
        <Pixel key={`${x}-${y}-${color}`} x={x} y={y} color={color} />
      ))}
    </svg>
  );
}
